### PR TITLE
wrapped xlib in try/except

### PR DESCRIPTION
**Pull request by michele-arrival**
credit to @CamiloHernandez

https://github.com/mmatl/pyrender/issues/117

### CODE REVIEW

**Comment by noamgat** [comment]
This is also blocking me from using pyrender in windows. Is there any reason why this hasn't been approved?

**Comment by CamiloHernandez** [comment]
@noamgat As far as I'm aware the reason this hasn't been merged is that this repo is somewhat inactive

**Comment by Vtn21** [comment]
I was having the same problem of #117 (Windows 10), and the proposed try/except solution works perfectly! Thanks everyone

@noamgat I also agree that this (or the more recent #162) should bem merged.

**Comment by catevita** [comment]
@mmatl  PTAL

**Comment by mmatl** [comment]
Hi all,

Apologies for the slow responses, been very busy lately. Merging these in now.

**Pull request merged**
