### PR TITLE
Add unproject_depth_map function for each camera class

### PR DESCRIPTION
**Pull request by ChenXuelinCXL**
The orthogonal camera uses a different unprojection matrix to recover the real depth values from the depth buffer.

Intrinsic and perspective camera share the same unprojection matrix.

I added the unproject_depth_map function for each camera class as I am coding in an object-oriented manner, feel free to modify if this is redundant. :)

### CODE REVIEW

**Comment by mmatl** [comment]
Hi! Thanks so much for the PR! Sorry for the delay, will look through this later today and update you.

**Comment by mmatl** [comment]
@ChenXuelinCXL I made a copy of this in a new branch -- could you look it over and let me know if it matches what you have? See the depth_linearization branch.

**Comment by ChenXuelinCXL** [comment]
hi, @mmatl , sorry for the delay. Just checked it, think it should be good, simply using a different matrix for orth. camera. Thanks.

**Comment by ChenXuelinCXL** [comment]
Hi, @mmatl , almost forget this PR, wondering if this is merged into the main branch... Maybe I missed something in this PR?

**Pull request closed without merging**
